services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./meu-projeto:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
